### ISSUE TITLE
Support dockerfile's with extension

### ISSUE THREAD

**Issue by alexbezugliy** [brpaz/hadolint-action#2]
Can we add a support to add Dockerfile.* files for linter checks? Assuming such Dockerfile file format was officially added by docker community. It seems that currently only default Dockerfile's are only supported.

**Comment by brpaz** [comment]
By default this extension is looking for Dockerfile only but you can override it by specificying the path/name to your Dockerfile.

The following should work:

```
steps:
    uses: brpaz/hadolint-action@master
   with:
       dockerfile: /path/to/dockerfile.test

```
