### ISSUE TITLE
How do I run multiple files

### ISSUE THREAD

**Issue by lukewiwa** [brpaz/hadolint-action#3]
Locally I can run something like this `hadolint docker/**/*Dockerfile` to capture all the dockerfiles in a directory but that doesn't seem to work in the pipeline.

Any suggestions?

**Comment by brpaz** [comment]
Hi. I didn't knew this was possible. This action simply passes the contents of the "dockerfile" action variable as an argument to the `hadolint` command so I guess it should work.

What error do you got?

**Comment by justinas-marozas** [comment]
I'm dealing with the same issue. Hadolint accepts both a glob and a list of filepaths and trying either in a github action end up with an error:

```
hadolint: ./**/Dockerfile: openBinaryFile: does not exist (No such file or directory)

OR

hadolint: ./a/Dockerfile ./b/Dockerfile ./c/Dockerfile: openBinaryFile: does not exist (No such file or directory)
```

One workaround I've found is to use the hadolint docker image in a `steps.run` like this:

```yaml
jobs:

  lint_dockerfiles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Dockerfiles
      run: docker run --rm -v $(pwd):/repo -i hadolint/hadolint sh -c "cd /repo && hadolint ./**/Dockerfile"
```

**Comment by brpaz** [comment]
This action just use the hadolint command as entrypoint. It supports a input argument "dockerfile" that is passed as single argument to the command.

While this was meant to be a path to a single Dockerfile, passing a glob should work I guess.

Something like this:

```yaml
     uses: brpaz/hadolint-action@master
      with:
         dockerfile:  "docker/**/*Dockerfile"
```

Unless the way GitHub parses arguments is doing something that makes it not working.

Anyway, PRs are welcome. I only ever used hadolint with a single line myself

**Comment by timbru31** [comment]
> Unless the way GitHub parses arguments is doing something that makes it not working.

That seems the case ;) - like Justinaz already stated, globs are resulting in `openBinaryFile: does not exist (No such file or directory)`.

**Comment by lukewiwa** [comment]
Honestly for multiple files I just went and did it from scratch using the hadolint container. Here's a github actions yaml snippet:

```yaml
  docker:
    runs-on: ubuntu-latest

    container: hadolint/hadolint

    steps:
      - uses: actions/checkout@v2
      - name: hadolint
        run: hadolint ./**/*Dockerfile
```

**Comment by mloskot** [comment]
@lukewiwa Do you still use your solution from https://github.com/hadolint/hadolint-action/issues/3#issuecomment-646366920 ? I tried it verbatim with the latest hadolint container and it failed for me:

```
Starting job container
  /usr/bin/docker pull hadolint/hadolint
  Using default tag: latest
  latest: Pulling from hadolint/hadolint
  4fc54f9b225a: Pulling fs layer
  4fc54f9b225a: Verifying Checksum
  4fc54f9b225a: Download complete
  4fc54f9b225a: Pull complete
  Digest: sha256:5bd624ce29f153036a3b03083af66f9ac040d2cb0673b2b4785394425e66f10b
  Status: Downloaded newer image for hadolint/hadolint:latest
  docker.io/hadolint/hadolint:latest
  /usr/bin/docker create --name 4949b719bd154b7681ce88e7bd783ca6_hadolinthadolint_39fe7c --label 5588e4 --workdir /__w/docker-images/docker-images --network github_network_33f62ade6b72421bbaf6fabd14b8b2d6  -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work":"/__w" -v "/home/runner/runners/2.277.1/externals":"/__e":ro -v "/home/runner/work/_temp":"/__w/_temp" -v "/home/runner/work/_actions":"/__w/_actions" -v "/opt/hostedtoolcache":"/__t" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" hadolint/hadolint "-f" "/dev/null"
  58579c5762e83e9ea0a1f98fc6a575bb3a5d474d1b7af65a461b3547940d3513
  /usr/bin/docker start 58579c5762e83e9ea0a1f98fc6a575bb3a5d474d1b7af65a461b3547940d3513
  Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "tail": executable file not found in $PATH: unknown
  Error: failed to start containers: 58579c5762e83e9ea0a1f98fc6a575bb3a5d474d1b7af65a461b3547940d3513
  Error: Docker start fail with exit code 1
```

**Comment by mloskot** [comment]
@justinas-marozas Do you still use your solution from https://github.com/hadolint/hadolint-action/issues/3#issuecomment-635424476 ?

It looks like the hadolint container changed, stripping everything but `hadolint` executable:

```
docker run --rm -i hadolint/hadolint sh -c "cd /repo && hadolint ./**/Dockerfile"
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "sh": executable file not found in $PATH: unknown.
```
```
docker run --rm -i hadolint/hadolint bash -c "cd /repo && hadolint ./**/Dockerfile"
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "bash": executable file not found in $PATH: unknown.
```

It also looks like `hadolint` command line changed and it only accepts single file, as this works fine:

```
docker run --rm -i -v %CD%:/repo hadolint/hadolint hadolint /repo/Dockerfile
```

but this does not

```
docker run --rm -i -v %CD%:/repo hadolint/hadolint hadolint /repo/**/Dockerfile
hadolint: /repo/**/Dockerfile: openBinaryFile: does not exist (No such file or directory)
```

**Comment by lorenzo** [comment]
@mloskot please use the debian based docker image if you need shell features for the container. You can find this information in the readme

**Comment by lorenzo** [comment]
I think the action needs to be changed so that it uses debian based image. @mloskot would you like to contribute this feature?

**Comment by mloskot** [comment]
@lorenzo Aha! I confess, as end-user and as I aimed for the container and not installation, I have not read further than just the https://github.com/hadolint/hadolint#how-to-use section
Thanks!

**Comment by lukewiwa** [comment]
@mloskot I confess I got the same error and moved on to using this https://github.com/marketplace/actions/hadolint-github-action

**Comment by GSvensk** [comment]
Debian or alpine images are needed to get a shell. https://github.com/hadolint/hadolint/issues/611

```
  lint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-debian
    steps:
    - uses: actions/checkout@v2
    - name: hadolint
      run: hadolint ./**/*Dockerfile*
```

**Comment by paulbarton90** [comment]
It appears the way you can get it to scan some of the files recursively is with the below configuration in your action. This should be the same as running it with `hadolint **/Dockerfile` locally.

```yaml
  lint-docker:
    runs-on: ubuntu-latest
    env:
      HADOLINT_RECURSIVE: "true"
    steps:
      - uses: actions/checkout@v3
      - name: Lint dockerfiles
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: "Dockerfile"
```

**Comment by mvs5465** [comment]
@paulbarton90 's solution worked for us
```
    env:
      HADOLINT_RECURSIVE: "true"
    steps:
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v2.0.0
        with:
          recursive: true
```

**Comment by 3bbbeau** [comment]
In my case, I can't use this action because it's built from a `Dockerfile` (using [ARC](https://github.com/actions/actions-runner-controller) in _Kubernetes_ mode). 

Debian image has `globstar` off by default, the following worked for me:

```yaml
jobs:
  lint:
    name: Dockerfile
    runs-on: ubuntu-latest
    container:
      image: hadolint/hadolint:2.12.0-debian
    steps:
      - uses: actions/checkout@v4
      - name: hadolint
        run: |
          shopt -s globstar
          hadolint **/*Dockerfile*
        shell: bash
```

**Comment by ItsJustRuby** [comment]
My use case was linting all Dockerfiles in my repository and this set up worked perfectly:

```yaml
jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "*.Dockerfile"
          recursive: true
```

**Comment by lkraav** [comment]
3.3.0: I was also wondering about this, but at least with `tj-actions/changed-files` multiple filenames seems to be working fine!

```yml
name: hadolint

on:
  pull_request:
    branches-ignore:
      - production
    paths:
      - '**/Dockerfile*'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v47
        id: changed-files
        with:
          files: '**/Dockerfile*'
      - uses: hadolint/hadolint-action@v3.3.0
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          dockerfile: ${{ steps.changed-files.outputs.all_changed_files }}
```

Result:

```
Run hadolint/hadolint-action@v3.3.0
  with:
    dockerfile: apps/admin-api/Dockerfile apps/admin/Dockerfile
    recursive: false
    output-file: /dev/stdout
    no-color: false
    no-fail: false
    verbose: false
    format: tty
    failure-threshold: info
...
Error: apps/admin-api/Dockerfile:15:1 unexpected 'H' expecting '#', '\', ADD, ARG, CMD, COPY, ENTRYPOINT, ENV, EXPOSE, FROM, HEALTHCHECK, LABEL, MAINTAINER, ONBUILD, RUN, SHELL, STOPSIGNAL, USER, VOLUME, WORKDIR, a pragma, at least one space, or end of input 
Error: apps/admin/Dockerfile:17:1 unexpected 'H' expecting '#', '\', ADD, ARG, CMD, COPY, ENTRYPOINT, ENV, EXPOSE, FROM, HEALTHCHECK, LABEL, MAINTAINER, ONBUILD, RUN, SHELL, STOPSIGNAL, USER, VOLUME, WORKDIR, a pragma, at least one space, or end of input 
Hadolint output saved to: /dev/stdout
```

Unclear if this issue #3 is actually solved at almost-2026?
